
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugIr9tIphDyVyUA2keCzIT4jpRor8MRY',
    authDomain: 'solino-e454f.firebaseapp.com',
    projectId: 'solino-e454f',
    storageBucket: 'solino-e454f.firebasestorage.app',
    messagingSenderId: '394173059992',
    appId: '1:394173059992:web:1335dbb2727388aac411ed',
    measurementId: 'G-D9JXH2L8HZ'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8CCfMt4qGtDyoC51v5OEgswYnhueD2uo',
    appId: '1:394173059992:android:61974d57aa52267ec411ed',
    messagingSenderId: '394173059992',
    projectId: 'solino-e454f',
    storageBucket: 'solino-e454f.firebasestorage.app'
  );
}
